# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    container_name: sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "hJtO2Gm2^Un#egr"
    ports: 
      - "1433:1433"